package com.arnyminerz.markdowntext

object Example {
    private const val exampleImageUrl = "https://picsum.photos/300/200"
    private const val exampleBadge = "https://raster.shields.io/badge/Label-Awesome!-success"
    private const val exampleLink = "https://example.com"

    val markdownTextExample = listOf(
        "This is a very long line for testing line wrapping. Line breaks should be inserted automatically for displaying long texts.",
        "# General formatting",
        "This is markdown text with **bold** content.",
        "This is markdown text with *italic* content.",
        "This is markdown text with **bold and *italic* texts**.",
        "This is markdown text with ~~strikethrough~~ content.",
        "Inline `code` annotations",
        "[This]($exampleLink) is a link.",
        "Automatic link: $exampleLink",
        "",
        "    This is some indented content",
        "    This is some indented content",
        "    This is some indented content",
        "",
        "# Header 1",
        "## Header 2",
        "### Header 3",
        "#### Header 4",
        "##### Header 5",
        "###### Header 6",
        "## Unordered lists",
        "- First",
        "* Second",
        "* Third",
        "- Fifth",
        "## Ordered lists",
        "1. First",
        "2. Second",
        "3. Third",
        "4. Fifth",
        "## Checkboxes",
        "- [ ] First",
        "- [ ] Second",
        "- [x] Third",
        "- [ ] Fifth",
        "--------",
        "/\\ That is a hr! /\\",
        "# Images",
        " ![Badge]($exampleBadge)![Badge]($exampleBadge)",
        "Here is a normal inline image: ![This is an image]($exampleBadge)",
        "But this one has a link: [![This is an image]($exampleBadge)]($exampleLink)",
        "This is a large block image:",
        "![Large image]($exampleImageUrl)",
        "'Quotes' are rendered \"correctly\" (I hope)",
        "",
        "| Column 1  | Column 2 | Column 3 |   |   |",
        "|-----------|----------|----------|---|---|",
        "| This      | Is       | A table  |   |   |",
        "| Formatted | In       | Markdown |   |   |",
        "|           |          |          |   |   |",
    ).joinToString(System.lineSeparator())
}