name: Release Drafter

on:
  push:
    branches:
      - master

jobs:
  update-release-draft:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create release
        uses: release-drafter/release-drafter@v5
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Prepare Gradle version file
        run: |
          truncate -s 0 markdown-text/version.gradle
          echo "ext {" >> markdown-text/version.gradle
          echo "  PUBLISH_VERSION=\"${{ steps.create_release.outputs.tag_name }}\"" >> markdown-text/version.gradle
          echo "}" >> markdown-text/version.gradle
          cat markdown-text/version.gradle
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: ":robot: Commit Changes"
          file_pattern: "gradle.properties markdown-text/version.gradle"
