name: 📦 Releaser

on:
  release:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: 🛎️ Checkout code
        uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 0
      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: 🔒 Prepare secure files
        run: |
          echo -n '${{ secrets.KEY_BASE64 }}' | base64 --decode > ${{ github.workspace }}/secring.gpg
          
          touch ./markdown-text/gradle.properties
          echo 'signing.keyId=${{ secrets.SIGNING_KEY_ID }}' > ./markdown-text/gradle.properties
          echo 'signing.password=${{ secrets.SIGNING_PASSWORD }}' > ./markdown-text/gradle.properties
          echo 'signing.secretKeyRingFile=${{ github.workspace }}/secring.gpg' > ./markdown-text/gradle.properties
      - name: ✈️ Run
        id: publish
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        run: ./gradlew publishAllPublicationsToMavenRepository
