name: 📦 Releaser

on:
  workflow_run:
    workflows: [ "Release Drafter" ]
    branches: [ master ]
    types:
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: 🛎️ Checkout code
        uses: actions/checkout@v3
        with:
          submodules: false
          fetch-depth: 0
      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: 🔒 Prepare secure files
        run: |
          touch ./local.properties
          echo 'signing.keyId=${{ secrets.SIGNING_KEY_ID }}' > ./local.properties
          echo 'signing.password=${{ secrets.SIGNING_PASSWORD }}' > ./local.properties
          echo 'signing.secretKeyRingFile=./secring.gpg' > ./local.properties
          echo 'ossrhUsername=${{ secrets.OSSRH_USERNAME }}' > ./local.properties
          echo 'ossrhPassword=${{ secrets.OSSRH_PASSWORD }}' > ./local.properties
          echo 'sonatypeStagingProfileId=${{ secrets.SONATYPE_STAGING_PROFILE_ID }}' > ./local.properties
      - name: ✈️ Run
        id: publish
        run: |
          yes | $ANDROID_HOME/tools/bin/sdkmanager "build-tools;33.0.0"
          bash ./gradlew publishReleasePublicationToSonatypeRepository
